# Generated by Django 6.0 on 2025-12-14 20:52

import django.db.models.deletion
import donations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=120)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('method', models.CharField(choices=[('card', 'Carte bancaire'), ('paypal', 'PayPal')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiée'), ('authorized', 'Autorisée'), ('failed', 'Échouée')], default='initiated', max_length=20)),
                ('reference', models.CharField(default=donations.models.generate_reference, max_length=24, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
