# Generated by Django 6.0 on 2025-12-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategory',
            name='icon',
            field=models.CharField(default='❤️', max_length=10),
        ),
    ]
