# Generated by Django 6.0 on 2025-12-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_media', '0002_usercategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmedia',
            name='published_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
