# Generated by Django 6.0 on 2025-12-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_media', '0003_savedmedia_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmedia',
            name='published_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
